[project]
name = "run-in-rhino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
rhino-watch = "server:main"

[tool.uv]
package = true

[tool.setuptools]
py-modules = ["server", "pipe", "rhino_watcher", "client"]
