[project]
name = "run-in-rhino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "websocket-client>=1.9.0",
    "websockets>=17.0.1",
]

[project.scripts]
in-rhino = "in_rhino:main"
rhino-watch = "server:main"

[tool.uv]
package = true

[tool.setuptools]
py-modules = ["in_rhino", "server", "pipe", "rhino_watcher", "client", "rhino_environment", "run_in_rhino"]
