import json
import secrets
import socket
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

from run_in_rhino.pipe import list_pipes, run_script


DEFAULT_RHINO_EXECUTABLE = Path(
    "/Applications/Rhino 8.app/Contents/MacOS/Rhinoceros"
)


@dataclass
class RhinoInstance:
    process: subprocess.Popen
    pipe_path: str
    document_path: Path
    startup_payload: dict

    def run_script(self, script_path=None, *, script=None):
        """Run a script through this instance's PID-owned RhinoCode pipe."""
        return run_script(
            script_path,
            pipe_path=self.pipe_path,
            script=script,
        )

    def stop(self, timeout=10):
        """Ask this Rhino to exit cleanly, with signals as a final fallback."""
        if self.process.poll() is not None:
            return

        try:
            run_script(
                script="import Rhino\nRhino.RhinoApp.Exit(False)\n",
                pipe_path=self.pipe_path,
            )
            self.process.wait(timeout=timeout)
            return
        except (ConnectionError, OSError, RuntimeError, subprocess.TimeoutExpired):
            pass

        self.process.terminate()
        try:
            self.process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            self.process.kill()
            self.process.wait(timeout=5)

    def __enter__(self):
        return self

    def __exit__(self, exception_type, exception, traceback):
        self.stop()


def _write_startup_callback(token, port, expected_document_path):
    source = f'''# This file is generated by run_in_rhino.app_control.instance.
import json
import os
import socket

import Rhino

expected_document_path = {str(expected_document_path)!r}
document = Rhino.RhinoDoc.ActiveDoc
payload = {{
    "token": {token!r},
    "process_id": os.getpid(),
    "document_path": document.Path if document else None,
    "expected_document_path": expected_document_path,
}}
with socket.create_connection(("127.0.0.1", {port}), timeout=10) as connection:
    connection.sendall((json.dumps(payload) + "\\n").encode("utf-8"))
'''
    with tempfile.NamedTemporaryFile(
        "w",
        prefix="run-in-rhino-ready-",
        suffix=".py",
        encoding="utf-8",
        delete=False,
    ) as callback_file:
        callback_file.write(source)
        return Path(callback_file.name)


def _receive_startup_payload(listener, process, timeout):
    listener.settimeout(0.25)
    deadline = time.monotonic() + timeout

    while time.monotonic() < deadline:
        return_code = process.poll()
        if return_code is not None:
            raise RuntimeError(
                "Rhino exited with code {} before its startup callback".format(
                    return_code
                )
            )

        try:
            connection, _address = listener.accept()
        except socket.timeout:
            continue

        with connection:
            connection.settimeout(5)
            chunks = []
            while True:
                chunk = connection.recv(4096)
                if not chunk:
                    break
                chunks.append(chunk)
                if b"\n" in chunk:
                    break

        message = b"".join(chunks).split(b"\n", 1)[0]
        if not message:
            raise RuntimeError("Rhino startup callback sent an empty message")
        return json.loads(message.decode("utf-8"))

    raise TimeoutError(
        "Rhino did not execute its startup callback within {} seconds".format(timeout)
    )


def _wait_for_process_pipe(process, timeout):
    expected_suffix = "rhinocode_remotepipe_{}".format(process.pid)
    deadline = time.monotonic() + timeout

    while time.monotonic() < deadline:
        return_code = process.poll()
        if return_code is not None:
            raise RuntimeError(
                "Rhino exited with code {} before its RhinoCode pipe appeared".format(
                    return_code
                )
            )

        matching_pipes = [
            pipe_path
            for pipe_path in list_pipes()
            if pipe_path.endswith(expected_suffix)
        ]
        if len(matching_pipes) == 1:
            return matching_pipes[0]
        if len(matching_pipes) > 1:
            raise RuntimeError(
                "Multiple RhinoCode pipes matched PID {}: {!r}".format(
                    process.pid,
                    matching_pipes,
                )
            )
        time.sleep(0.1)

    raise TimeoutError(
        "No RhinoCode pipe appeared for Rhino PID {} within {} seconds".format(
            process.pid,
            timeout,
        )
    )


def _stop_failed_launch(process, pipe_path):
    if process.poll() is not None:
        return

    if pipe_path is None:
        expected_suffix = "rhinocode_remotepipe_{}".format(process.pid)
        matching_pipes = [
            candidate
            for candidate in list_pipes()
            if candidate.endswith(expected_suffix)
        ]
        if len(matching_pipes) == 1:
            pipe_path = matching_pipes[0]

    if pipe_path is not None:
        try:
            run_script(
                script="import Rhino\nRhino.RhinoApp.Exit(False)\n",
                pipe_path=pipe_path,
            )
            process.wait(timeout=10)
            return
        except (ConnectionError, OSError, RuntimeError, subprocess.TimeoutExpired):
            pass

    process.terminate()
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=5)


def _find_running_processes(executable):
    result = subprocess.run(
        ["ps", "-axo", "pid=,command="],
        check=True,
        capture_output=True,
        text=True,
    )
    executable_prefix = str(executable) + " "
    process_ids = []
    for line in result.stdout.splitlines():
        pid_text, separator, command = line.strip().partition(" ")
        command = command.strip()
        if separator and (
            command == str(executable) or command.startswith(executable_prefix)
        ):
            process_ids.append(int(pid_text))
    return process_ids


def _active_documents_by_process(executable):
    rhinocode = executable.parents[1] / "Resources/bin/rhinocode"
    if not rhinocode.is_file():
        return {}

    try:
        result = subprocess.run(
            [str(rhinocode), "list", "--json"],
            check=True,
            capture_output=True,
            text=True,
            timeout=5,
        )
        instances = json.loads(result.stdout)
    except (json.JSONDecodeError, OSError, subprocess.SubprocessError):
        return {}

    documents = {}
    for instance in instances:
        process_id = instance.get("processId")
        active_document = instance.get("activeDoc") or {}
        document = active_document.get("location") or active_document.get("title")
        if process_id is not None and document:
            documents[int(process_id)] = document
    return documents


def _running_process_message(executable, process_ids):
    active_documents = _active_documents_by_process(executable)
    process_lines = []
    for process_id in process_ids:
        document = active_documents.get(process_id, "<active document unavailable>")
        process_lines.append("  PID {}: {}".format(process_id, document))

    return (
        "Rhino is already running:\n{}\n"
        "Rhino for macOS does not support a second same-version process; close "
        "the listed session before launching a dedicated test instance."
    ).format("\n".join(process_lines))


def launch_rhino(
    document_path,
    *,
    executable=DEFAULT_RHINO_EXECUTABLE,
    startup_timeout=60,
):
    """Launch Rhino and wait for its startup Python callback and PID-owned pipe."""
    executable = Path(executable).expanduser().resolve()
    document_path = Path(document_path).expanduser().resolve()
    if not executable.is_file():
        raise FileNotFoundError("Rhino executable not found: {}".format(executable))
    if not document_path.is_file():
        raise FileNotFoundError("Rhino document not found: {}".format(document_path))

    running_processes = _find_running_processes(executable)
    if running_processes:
        raise RuntimeError(
            _running_process_message(executable, running_processes)
        )

    token = secrets.token_urlsafe(32)
    callback_path = None
    process = None
    pipe_path = None

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        listener.bind(("127.0.0.1", 0))
        listener.listen(1)
        port = listener.getsockname()[1]
        callback_path = _write_startup_callback(token, port, document_path)
        macro = "_StartScriptServer _-ScriptEditor _R {}".format(callback_path)

        try:
            process = subprocess.Popen(
                [
                    str(executable),
                    str(document_path),
                    "-nosplash",
                    "-runscript={}".format(macro),
                ],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            payload = _receive_startup_payload(
                listener,
                process,
                startup_timeout,
            )
            pipe_path = _wait_for_process_pipe(process, startup_timeout)

            if payload.get("token") != token:
                raise RuntimeError("Rhino startup callback returned the wrong token")
            if payload.get("process_id") != process.pid:
                raise RuntimeError(
                    "Rhino startup callback PID {} did not match launched PID {}".format(
                        payload.get("process_id"),
                        process.pid,
                    )
                )
            callback_document = payload.get("document_path")
            if not callback_document:
                raise RuntimeError("Rhino startup callback had no active document")
            if Path(callback_document).resolve() != document_path:
                raise RuntimeError(
                    "Rhino opened {!r}, expected {!r}".format(
                        callback_document,
                        str(document_path),
                    )
                )

            return RhinoInstance(
                process=process,
                pipe_path=pipe_path,
                document_path=document_path,
                startup_payload=payload,
            )
        except Exception:
            if process is not None:
                _stop_failed_launch(process, pipe_path)
            raise
        finally:
            if callback_path is not None:
                callback_path.unlink(missing_ok=True)
